# Creates a new image version when a new version of the devvm.json file is created.
name: Create Image Version

# Run the workflow only when the devvm.json file has been updated in the master branch.
on:
  push:
    branches: [ master ]
    paths: .test/test.json

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        env:
          ENDPOINT:  http://localhost:53760/api/v1/environments
          TYPE: CloudEnvironment
          TOKEN: ${{github.token}}
          MONIKER: ${{github.repositoryUrl}}
          FRIENDLYNAME: ${{github.sha}}
          QueueResourceAllocation: false
          LocalCredentialHelper: false
        run: |
          repoUrl=$("$MONIKER" | cut -f 1,2 --d '.' )
          curl -X POST "$ENDPOINT" 
           -H "Content-Type: application/json" 
           -H "Authorization: github $TOKEN"
           -H "accept: */*"
          --data '{
                  "Type": "CloudEnvironment",
                 "FriendlyName": "$FRIENDLYNAME",
                "ExperimentalFeatures": {
                                         "QueueResourceAllocation": false,
                                         "LocalCredentialHelper": false,
                                         "EnableDynamicHttpsDetection": false,
                                         "UnifiedContainerImplementation": false,
                                         "UsePrebuild": false
                                         },
                  "Features": {},
                  "Seed": {
                           "type": "Git",
                           "moniker": "$repoUrl",
                           "gitConfig": null,
                           "recurseClone": false
                           },
                   "Personalization": {
                                       "dotfilesRepository": null,
                                       "dotfilesTargetPath": null,
                                       "dotfilesInstallCommand": null
                                       },
                    "ContainerImage": null,
                    "Connection": {
                                  "sessionId": null,
                                  "sessionPath": null,
                                  "serviceUri": null,
                                  "relayEndpoint": null,
                                  "relaySas": null,
                                  "sessionToken": null,
                                  "hostPublicKeys": null
                                  },
                     "SkuName": "standardLinux32gb",
                     "PlanId": "/subscriptions/8def34ce-053c-43ba-8501-37599fb7f010/resourceGroups/github-nexus/providers/Microsoft.Codespaces/plans/github-vs-plan",
                     "AutoShutdownDelayMinutes": 240,
                     "Secrets": [],
                    "DevContainerJson": null,
                    "Label": null,
                    "HasDevcontainerJson": false,
                    "Identity": null,
                    "GithubEnvironmentEndpoint": null,
                    "CreateAsPrebuild": true
                 }'
