# Creates a new image version when a new version of the devvm.json file is created.
name: Create Prebuild

# Run the workflow only when the devvm.json file has been updated in the master branch.
on:
  workflow_dispatch: 
    branch: main
    
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        env:
          ENDPOINT: https://api.github.com/vscs_internal/user/${{github.actor}}/api/v1/environments
          TYPE: CloudEnvironment
          TOKEN: ${{github.token}}
          MONIKER: ${{github.event.repository.html_url}}
          FRIENDLYNAME: ${{github.sha}}
          QueueResourceAllocation: false
          LocalCredentialHelper: false
        run: |
          curl "$ENDPOINT" 
          -H "accept: */*" 
             
