# Creates a new image version when a new version of the devvm.json file is created.
name: Create Image Version

# Run the workflow only when the devvm.json file has been updated in the master branch.
on:
  push:
    branches: [ master ]
    paths: .test/test.json

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        env:
          ENDPOINT:  http://localhost:53760/api/v1/environments
          TYPE: CloudEnvironment
          TOKEN: ${{github.token}}
          MONIKER: ${{github.repositoryUrl}}
          FRIENDLYNAME: ${{github.sha}}
          QueueResourceAllocation: false
          LocalCredentialHelper: false
        run: curl -X POST "$ENDPOINT" -H "accept: application/json"
